#!/bin/bash
set -euo pipefail

mkdir -p bin build/bin dist
if [ -e "./scripts/${1:-}" ]; then
    ./scripts/"$@"
else
    "$@"
fi

if [ -n "${DAPPER_UID:-}" ] && [ -n "${DAPPER_GID:-}" ]; then
    chown -R "${DAPPER_UID}:${DAPPER_GID}" .
fi
