#!/bin/bash
set -euo pipefail

source "$(dirname "$0")/version"

cd "$(dirname "$0")/.."

DIST=$(pwd)/dist/artifacts

mkdir -p "${DIST}/${VERSION}" "${DIST}/latest"

for i in build/bin/*; do
    if [ ! -e "$i" ]; then
        continue
    fi

    BASE=build/archive
    DIR=${BASE}/pasturestack-${VERSION}

    rm -rf "$BASE"
    mkdir -p "$BASE" "$DIR"

    EXT=
    if [[ $i =~ .*windows.* ]]; then
        EXT=.exe
    fi

    cp "$i" "${DIR}/pasturestack${EXT}"

    arch=$(echo "$i" | cut -f2 -d_)
    mkdir -p "${DIST}/${VERSION}/binaries/${arch}"
    mkdir -p "${DIST}/latest/binaries/${arch}"
    cp "$i" "${DIST}/${VERSION}/binaries/${arch}/pasturestack${EXT}"
    if [ -z "${EXT}" ]; then
        gzip -c "$i" > "${DIST}/${VERSION}/binaries/${arch}/pasturestack.gz"
        xz -c "$i" > "${DIST}/${VERSION}/binaries/${arch}/pasturestack.xz"
    fi

    rm -rf "${DIST}/latest/binaries/${arch}"
    mkdir -p "${DIST}/latest/binaries"
    cp -rf "${DIST}/${VERSION}/binaries/${arch}" "${DIST}/latest/binaries"

    (
        cd $BASE
        NAME=$(basename "$i" | sed 's/_/-/g')
        if [ -z "$EXT" ]; then
            tar cvzf "${DIST}/${VERSION}/${NAME}-${VERSION}.tar.gz" .
            cp "${DIST}/${VERSION}/${NAME}-${VERSION}.tar.gz" "${DIST}/latest/${NAME}.tar.gz"

            tar cvJf "${DIST}/${VERSION}/${NAME}-${VERSION}.tar.xz" .
            cp "${DIST}/${VERSION}/${NAME}-${VERSION}.tar.xz" "${DIST}/latest/${NAME}.tar.xz"
        else
            NAME=$(echo $NAME | sed 's/'${EXT}'//g')
            zip -r "${DIST}/${VERSION}/${NAME}-${VERSION}.zip" *
            cp "${DIST}/${VERSION}/${NAME}-${VERSION}.zip" "${DIST}/latest/${NAME}.zip"
        fi
    )
done


ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd package

TAG=${TAG:-${VERSION}${SUFFIX}}
IMAGE_NAME=${IMAGE_NAME:-${REPO:-ghcr.io/pasturestack}/cli}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi

cp ../bin/pasturestack .
cp ../LICENSE .
cp ../SECURITY.md .
cp ../ORIGIN.md .
cp ../COMPATIBILITY.md .

docker_build_network_arg=()
if [ -n "${DOCKER_BUILD_NETWORK:-}" ]; then
    docker_build_network_arg=(--network="${DOCKER_BUILD_NETWORK}")
fi

IMAGE="${IMAGE_NAME}:${TAG}"
DOCKER_BUILDKIT="${DOCKER_BUILDKIT:-0}" docker build "${docker_build_network_arg[@]}" \
    --build-arg UBUNTU_MIRROR="${UBUNTU_MIRROR:-http://archive.ubuntu.com/ubuntu}" \
    --build-arg IMAGE_VERSION="${TAG}" \
    -t "${IMAGE}" .

mkdir -p ../dist
echo "${IMAGE}" > ../dist/images
echo "Built ${IMAGE}"
