#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

echo Running validation

PACKAGES=$(go list ./... | grep -Ev '(/vendor/)' || true)

echo Running: go vet
go vet ${PACKAGES}
echo Running: go fmt
test -z "$(gofmt -l -s $(find . -name '*.go' | grep -v -e ./.git -e ./vendor -e ./.trash-cache) | tee /dev/stderr)"
