#!/bin/bash

if [ -n "${VERSION_OVERRIDE:-}" ]; then
    VERSION="${VERSION_OVERRIDE}"
else
    DIRTY=""
    if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
        DIRTY="-dirty"
    fi
    COMMIT=$(git rev-parse --short HEAD)
    GIT_TAG=${TAG:-${DRONE_TAG:-$(git tag -l --contains HEAD | head -n 1)}}

    if [ -n "$GIT_TAG" ]; then
        VERSION=$GIT_TAG
    else
        VERSION="${COMMIT}"
    fi
fi
